<a href="https://colab.research.google.com/github/Anmolrbd/FDS_Lab/blob/main/Python_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Variables
x = 10
y = 5
print("X = " + str(x) + " Y = " + str(y))

X = 10 Y = 5


# **Mini exercises for variables**

1. **Performing basic Mathematic operations**

In [ ]:

addition = x + y
subtraction = x - y
multiplication = x * y
division = x / y
exponent = x ** y
print("Addition: " + str(addition))
print("Subtraction: " + str(subtraction))
print("Multiplication: " + str(multiplication))
print("Division: " + str(division))
print("Exponent: " + str(exponent))

Addition: 15
Subtraction: 5
Multiplication: 50
Division: 2.0
Exponent: 100000


**2. Swapping values by using and without using a third variable**

In [ ]:


#using a third varibale
value1 = 10
value2 = 20
print("Before swapping: " + str(value1) + " " + str(value2))
temp = value1
value1 = value2
value2 = temp
print("After swapping: " + str(value1) + " " + str(value2))

#without using a third variable
num1 = 50
num2 = 60
print("Before swapping: " + str(num1) + " " + str(num2))
num1 = num1 + num2
num2 = num1 - num2
num1 = num1 - num2
print("After swapping: " + str(num1) + " " + str(num2))

Before swapping: 10 20
After swapping: 20 10
Before swapping: 50 60
After swapping: 60 50


**3. Finding the area of shapes**

In [ ]:
radius = 30
circle_area = 3.14 * radius ** 2

rectangle_length = 10
rectangle_breadth = 20
rectangle_area = rectangle_length * rectangle_breadth

square_length = 5
square_area = square_length ** 2

print(circle_area)
print(rectangle_area)
print(square_area)

2826.0
200
25


**4. Converting Celsius into Fahrenheit**

In [ ]:
celsius = 56
f = (celsius * 9/5) + 32
print(f)


132.8


**Challenges / Things to improve: Remembering variable rules, practicing print statements, use of str() while displaying numbers with strings**


# **1. Built in Data types**

Integer(int) = number without any decimal values

In [ ]:
#int

x = 4
print(x)
print(type(x))

4
<class 'int'>


Floating point(float) = Number containing decimal values

In [ ]:
#float

x = 23.5
print(x)
print(type(x))

23.5
<class 'float'>


String(str) = sequences of characters written enclosed in '' or ""

In [ ]:
string1 = "Apple"
string2 = "123"
print(type(string1))
print(type(string2))

<class 'str'>
<class 'str'>


Boolean(bool) = states where the condition is true or false

In [ ]:
istrue = True
isFalse = False
print(type(isFalse))
print(type(istrue))

<class 'bool'>
<class 'bool'>


# **2. Input / Output**

input(): allows the user to enter data

Note: The value obtained from the input is always a string



In [ ]:
x = input("Enter any number: ")
print(x)
print(type(x))

Enter any number: 45
45
<class 'str'>


In [ ]:
#taking two numbers as input and finding the sum
num1 = input("Enter first number: ")
num1 = int(num1)
num2 = int(input("Enter second number: "))
sum = num1 + num2
print(sum)

#int cannot be added to the string literals, so it must be converted to string
#before addition
print("Sum: " + str(sum))

Enter first number: 30
Enter second number: 40
70
Sum: 70


# **3. Type Conversion**

Converting one data type into another data type, either implicitly or explicitly.

Note: The value obtained from input() returns a string, so inorder to obtain the int value, we have to explicitly change the data type from string to int.

In [ ]:
x = 45
print(type(x))
x = str(x)
print(type(x))
x = float(x)
print(type(x))

<class 'int'>
<class 'str'>
<class 'float'>


# **Mini exercises**

**1. Ask the user to enter their name and age, then display it.**

In [ ]:
name = input("Enter your name: ")
age = input("Enter your age: ")
print("Name: " + name)
print("Age: " + age)


Enter your name: Anmol
Enter your age: 19
Name: Anmol
Age: 19


**2. Find Simple Interest.**

In [ ]:
principle = int(input("Enter principle: "))
time = int(input("Enter time: "))
rate = int(input("Enter rate: "))
SI = (principle * time * rate) / 100
print("Simple Interest: " + str(SI))

Enter principle: 200000
Enter time: 2
Enter rate: 3
Simple Interest: 12000.0


**3. Finding average marks**

In [ ]:
number_of_subjects = int(input("Enter the number of subjects: "))
total_marks = int(input("Enter the total marks obtained: "))
average = total_marks / number_of_subjects
print("Average marks: " + str(average))

Enter the number of subjects: 3
Enter the total marks obtained: 250
Average marks: 83.33333333333333


## learning numpy


In [ ]:
import numpy as np

In [ ]:
array1D = np.array([1,2,3,4])
print("1D array:", array1D)

array2D = np.array([[1,2,3],[4,5,6]])
print("2D array: ", array2D)

1D array: [1 2 3 4]
2D array:  [[1 2 3]
 [4 5 6]]


In [ ]:
import time

start = time.time()

alist = [value * 2 for value in range(100000)]
print("Time for list: " , time.time() - start)

start = time.time()
nparray = np.arange(100000)
print("Time for numpy: ", time.time() - start)

Time for list:  0.006422758102416992
Time for numpy:  0.0007865428924560547


### np.zeros(x,y) - generates a x*y matrix of elements 0

### np.ones(x,y) - generates a x*y matrix of elements 1

### np.random.random - generates a random number between 0 and 1

### np.random.random(x,y) - genrates a x*y matrix of elements between 0 and 1

In [ ]:
import numpy as np

zeros = np.zeros((2,3))
print(zeros)

ones = np.ones((4,4))
print(ones)

randvalue = np.random.random() #generates random value between 0 and 1
print(randvalue)

custom = np.random.random((2,3)) #generates an matrix of given size of value between 0 and 1
print(custom)

matrix1 = np.full((2,3),7)
print(matrix1)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
0.21927810872142495
[[0.64342396 0.88415323 0.91051427]
 [0.0566985  0.90269183 0.0171468 ]]
[[7 7 7]
 [7 7 7]]


## Array, Matrix, and Tensor


In [ ]:
array1D = np.array([1,2,3])
print("Array: ", array1D)

matrix = np.array([
    [1,2,3],
    [4,5,6]
])
print("Matrix:\n", matrix)

tensor = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print("Tensor:\n", tensor)

Array:  [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Array properties

In [ ]:
import numpy as np

array1D = np.array([1,2,3])
print("1D array")
print("Shape: ", array1D.shape)
print("Dimension: ", array1D.ndim)
print("Dtype: ", array1D.dtype)
print("Size: ", array1D.size)

print("\n2D array/matrix")

matrix = np.array([
    [1,2,3],
    [4,5,6]
])
print("Shape: ", matrix.shape)
print("Dimension: ", matrix.ndim)
print("Dtype: ", matrix.dtype)
print("Size: ", matrix.size)

print("\n3D array")

tensor = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

print("Shape: ", tensor.shape)
print("Dimension: ", tensor.ndim)
print("Dtype: ", tensor.dtype)
print("Size: ", tensor.size)


1D array
Shape:  (3,)
Dimension:  1
Dtype:  int64
Size:  3

2D array/matrix
Shape:  (2, 3)
Dimension:  2
Dtype:  int64
Size:  6

3D array
Shape:  (2, 2, 3)
Dimension:  3
Dtype:  int64
Size:  12


In [ ]:
arr = np.arange(10)
print("Original array: ", arr)
print("Size: ", arr.size)

reshaped = arr.reshape((2,5))
print("Reshaped array:\n", reshaped)

flattened = reshaped.flatten()
print("Flat array: ", flattened)

flattened[7] = 60
print(flattened)
print(reshaped)

ravel = reshaped.ravel()
print("Raveled: \n", ravel)
ravel[5] = 45

print(ravel)
print(reshaped)

arr2 = np.arange(0,12,2)
print("\nNew array:\n",arr2)
reshapearr2 = arr2.reshape(2,3)
print("Reshaped array: \n", reshapearr2)

transpose = reshapearr2.T
print("Transpose: \n", transpose)



Original array:  [0 1 2 3 4 5 6 7 8 9]
Size:  10
Reshaped array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Flat array:  [0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6 60  8  9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
Raveled: 
 [0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 45  6  7  8  9]
[[ 0  1  2  3  4]
 [45  6  7  8  9]]

New array:
 [ 0  2  4  6  8 10]
Reshaped array: 
 [[ 0  2  4]
 [ 6  8 10]]
Transpose: 
 [[ 0  6]
 [ 2  8]
 [ 4 10]]


## Array operations

In [ ]:
array = np.array([1,2,3,4,5,6,7,8,9,10])

print("Basic slicing:", array[2:6])
print("Negative indexing:", array[-4])
print("Negative slicing:", array[-4:])

In [ ]:
array2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Specific indexing, first row second element:", array2d[0,1])
print("Entire third row:", array2d[2])
print("Entire second column:", array2d[:,1])

## Array sorting

In [ ]:
unsorted_1D_array = np.array([9,3,6,1,2,0,5,10])
print("Sorted array", np.sort(unsorted_1D_array))

unsorted_2D_array = np.array([
    [7,4,3],
    [2,0,1],
    [1,5,8]
])
print("unsorted array:\n", unsorted_2D_array)
print("Sorted array 2d axis=0:\n", np.sort(unsorted_2D_array, axis=0))
print("Sorted array 2d axis=1:\n", np.sort(unsorted_2D_array, axis=1))

## Flitering

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers:", even_numbers)
